name: sqlite_controller
description: A Singleton for Sqlite use
version: 0.7.0+1
homepage: https://github.com/GitHubStuff/sqlite_controller

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_exception:
    git:
      url: https://github.com/GitHubStuff/app_exception.git
  flutter:
    sdk: flutter
  path_provider: ^1.6.8
  sqflite: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: